function Asn() { 
	this.Id = null;
	this.Folio = null;
	this.Id_cliente = null;
	this.Id_almacen = null;
	this.Fecha_arribo = null;
	this.Hora_arribo = null;
	this.Operador = null;
	this.Sello = null;
	this.Sello_c_w_ma = null;
	this.Id_transporte_linea = null;
	this.Id_transporte_tipo = null;
	this.Placa = null;
	this.Caja = null;
	this.Cont_1 = null;
	this.Cont_2 = null;
	this.IsActive = null;
}; 
module.exports = Asn;