function Asn() { 
	this.AsnId = null;
	this.AsnFolio = null;
	this.ClienteId = null;
	this.AlmacenId = null;
	this.AsnFechaArribo = null;
	this.AsnHoraArribo = null;
	this.AsnOperador = null;
	this.AsnSello = null;
	this.AsnSelloClienteDateTime = null;
	this.TransporteLineaId = null;
	this.TransporteTipoId = null;
	this.AsnPlaca = null;
	this.AsnCaja = null;
	this.AsnContenedorUno = null;
	this.AsnContenedorDos = null;
	this.IsActive = null;
}; 
module.exports = Asn;